### ISSUE TITLE
Unsafe builder use

### ISSUE THREAD

**Issue by kerams** [crowded/ply#17]
Hello, I'd like to get a clarification on when to avoid unsafe builders with regards to the execution bubble.

> It's rare that methods do anything with async locals or synchronization contexts, even in C#. So if you know **anything you use** doesn't do that either then there's nothing inherently unsafe about using the Unsafe CEs as you don't need any execution bubble for correctness.

What exactly does the bold part refer to? Use of synchronization contexts in my user code or also 3rd party library methods that I'm awaiting? For instance, given this code

```fsharp
let setupConnection () = unitVtask {
    cmd.Connection <- new NpgsqlConnection (connectionString)
    do! cmd.Connection.OpenAsync ()
    do! cmd.PrepareAsync ()
    if cfg.UseNetTopologySuite then cmd.Connection.TypeMapper.UseNetTopologySuite () |> ignore }
```

If I am unsure whether Npgsql uses synchronization contexts and want to play it safe, do I have to refrain from using unsafe builders all the way down? Or is it perfectly fine because `OpenAsync` and `PrepareAsync ` return tasks with their own bubbles?

Additionally, I assume `Unsafe.uply` is the most performant of the unsafe builders. Does it have any drawbacks compared to the rest of them when used internally in a library (i.e. it does not leak through the API)?

**Comment by NinoFloris** [comment]
You should be fine to use unsafe builders for npgsql, the non-unsafe CEs really only perform extra cleanup in a specific case once tasks complete.

Really what happens is, every C# async await method will do cleanup regardless and as npgsql is entirely C# any change npgsql makes is neatly reverted once its own returned tasks complete.

Any change to async locals or sync ctx changes within your unsafe builder — either as a direct expression, sync method call, or in another unsafe builder — will still take effect, however its cleanup once *your task* completes can't be guaranteed, this can cause you to leak (some of) these changes up the stack.

This used to be a thing with aspnet core as well, you could get async locals to leak onto the connection instead of the request, causing them to show in all log entries for the duration of the connection, instead of the intended request scope.

Easiest example I can give you is something like (somewhat pseudo code):

```fs
// Logger scopes flow via an AsyncLocal, you can Dispose() a scope earlier than the method scope.
// Otherwise unwinding of a normal async stack causes it to be dropped once cleanup is done.
let addLoggerScope (logger: ILogger) =
    logger.BeginScope("Scope") |> ignore

let unsafemiddleware ctx next = 
    (uvtask {
        addLoggerScope (ctx.GetService<_>)
    }).AsTask() :> Task
    
let middleware ctx next = unitTask {
    addLoggerScope (ctx.GetService<_>)
}

let unsafebutstillcleanedupmiddleware ctx next = 
    (uvtask {
        // Task.Yield forces addLoggerScope to always happen in the continuation of the (Value)Task and it will be cleaned up.
        do! Task.Yield()
        addLoggerScope (ctx.GetService<_>)
    }).AsTask() :> Task

let routestart middleware ctx next = task {
    do! middleware ctx next
    (ctx.GetService<ILogger>).LogInformation("Remaining scopes")
}  

let retainedScopes = routestart unsafemiddleware
let emptyScopes = routestart middleware
let emptyScopes2 = routestart unsafebutstillcleanedupmiddleware

```

If you are just interested in ignoring or respecting sync contexts, picking the NonAffine or Affine builders namespace respectively helps you do so, NonAffine will insert `ConfigureAwait(false)` on every bind (unless binding to an already configured awaiter).

>Additionally, I assume Unsafe.uply is the most performant of the unsafe builders. Does it have any drawbacks compared to the rest of them when used internally in a library (i.e. it does not leak through the API)?

Yes it's indeed the fastest option, one allocation per bind (if not completed yet) and no intermediate state machines! 
And no, it does not leak, the entirety of Ply internally runs on them :)

Hope it helps, it's complicated stuff unfortunately but feel free to ask for any clarification!

**Comment by kerams** [comment]
Good stuff. Thanks for the explanation and the library.
