### ISSUE TITLE
MIssingMethodException

### ISSUE THREAD

**Issue by JonCanning** [crowded/ply#3]
I'm seeing this error when calling a netstandard2.0 lib from a netcore2.2 app using the nuget package

```System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<!!0> Ply.TplPrimitives.run(Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Ply.Ply`1<!!0>>)```

However, it works if I import the source

**Comment by NinoFloris** [comment]
Got it, investigating... 

`dotnet pack` completes both builds (ns2.0 and nca2.1) without errors, might be a weird multi-targetting issue.

**Comment by NinoFloris** [comment]
Fix is coming up in v0.1.5

With multi-targeting the assembly that will be copied into output ultimately is the one closest to the root project target framework, which makes sense as you'd want to have as much surface area avaliable to you as your projects can handle. 

Due to type inference however we would compile `run` in two flavors, one returning `Task` and the other returning `ValueTask`. Those are both correct within Ply as a single project and lead to a succesful compilation for ns2.0 and nca2.1. 

Once you start mixing netstandard projects with a dependent project that is netcoreapp2.1+ however, the assembly in the output directory would now have the `ValueTask` run method while the netstandard library you're using expects that to still return `Task`.

The solution was to have two fixed return type functions `runAsTask` and `run` which do the right thing under the internal differences in Ply for ns2.0 and nca2.1.

I have added a few test projects exercising this case to prevent it from happening again.

Thanks for the issue!

**Comment by NinoFloris** [comment]
Letting you know, 0.1.5 is listed on nuget now! Let me know via FSSF slack how it goes :)
